#!/bin/bash
# Add-on entrypoint: bring up PipeWire, point an RTP sink at the audio router,
# then hand over to the cast receiver.
#
# Mirrors the audio-router add-on's run.sh (private D-Bus, pipewire, wireplumber,
# then the application) with one addition: the RTP sink is generated here from the
# add-on options, because a static drop-in cannot know the configured host/port.
set -euo pipefail

# --- options ----------------------------------------------------------------
# The router add-on has no options at all, so there is no bashio in this image
# family; python3 is here for the yt-dlp venv anyway, so it does the parsing.
# `get` prints the value or the supplied default when absent/null/empty.
opt() {
  python3 - "$1" "${2-}" <<'PY'
import json, sys
key, default = sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else ""
try:
    with open("/data/options.json") as f:
        value = json.load(f).get(key)
except (OSError, ValueError):
    value = None
if value is None or value == "":
    value = default
# JSON booleans arrive as Python bools, and printing those yields "True"/"False"
# — which no shell comparison against "true" ever matches. That silently disabled
# metadata reporting on the first deploy despite the option defaulting to true.
if isinstance(value, bool):
    value = "true" if value else "false"
print(value)
PY
}

DEVICE_NAME="$(opt device_name "Musik (Home Assistant)")"
RTP_HOST="$(opt rtp_host 127.0.0.1)"
RTP_PORT="$(opt rtp_port 46002)"
DIAL_PORT="$(opt dial_port 8098)"
CIPHER_URL="$(opt cipher_url)"
# `none`/`off`/`false` disable remote solving explicitly, matching the Pi's
# `--cipher-url none`. Worth having even though the default is now empty: a value that
# was saved once stays in the user's options, and typing a word is a reliable way to
# override it — clearing the field only removes the key, which is how the old default
# kept coming back.
case "$(printf '%s' "$CIPHER_URL" | tr '[:upper:]' '[:lower:]')" in
  none|off|false|disabled) CIPHER_URL="" ;;
esac
POT_URL="$(opt pot_provider_url)"
BIND_ADDRESS="$(opt bind_address)"
REPORT_METADATA="$(opt report_metadata true)"
LOG_LEVEL="$(opt log_level info)"

echo "[run] YouTube Music receiver ${ADDON_VERSION:-dev}: DIAL '${DEVICE_NAME}' on :${DIAL_PORT}, audio -> ${RTP_HOST}:${RTP_PORT}, admin page on :8097"

# --- PipeWire ---------------------------------------------------------------
export XDG_RUNTIME_DIR=/run/pipewire
mkdir -p "$XDG_RUNTIME_DIR"
chmod 700 "$XDG_RUNTIME_DIR"
# A restart reuses the container's writable /run, so sockets from an unclean exit
# would block the daemon. Same reasoning as the router's run.sh.
rm -f "$XDG_RUNTIME_DIR"/pipewire-0 "$XDG_RUNTIME_DIR"/pipewire-0-manager

# The RTP sender, as a real Audio/Sink node that mpv plays into. No null sink and
# no loopback in front of it: mpv is an ordinary playback client, and an always-on
# loopback would transmit silence around the clock. With no client the sink is idle
# and nothing is sent.
mkdir -p /etc/pipewire/pipewire.conf.d
cat > /etc/pipewire/pipewire.conf.d/60-ytmusic-rtp.conf <<EOF
# Generated by run.sh from the add-on options — edit those, not this file.
context.modules = [
  { name = libpipewire-module-rtp-sink
    args = {
      destination.ip = "${RTP_HOST}"
      destination.port = ${RTP_PORT}
      sess.media = "audio"
      audio.format = "S16LE"
      # 48 kHz end to end: YouTube audio is natively 48 kHz (opus) and so is the
      # router's graph, so nothing resamples anywhere on this path.
      audio.rate = 48000
      audio.channels = 2
      stream.props = {
        node.name = "ytm-out"
        node.description = "YouTube Music to RTP (sender)"
        media.class = "Audio/Sink"
      }
    }
  }
]
EOF

# Private per-container session bus; wireplumber hard-depends on having one.
eval "$(dbus-launch --sh-syntax)"

pipewire &
for _ in $(seq 1 100); do
  [ -S "$XDG_RUNTIME_DIR/pipewire-0" ] && break
  sleep 0.1
done
wireplumber &
sleep 1

if ! pw-cli ls Node 2>/dev/null | grep -q 'node.name = "ytm-out"'; then
  echo "[run] WARNING: the ytm-out sink did not load — check the module args above"
fi

# --- resolver freshness -----------------------------------------------------
# YouTube breaks yt-dlp extractors on its own schedule, so refresh at boot rather
# than only at image build. Backgrounded on purpose: it needs the network and
# takes tens of seconds on a Pi, and the receiver must be discoverable immediately.
(
  if /opt/ytdlp/bin/pip install --quiet --upgrade yt-dlp yt-dlp-ejs yt-dlp-remote-cipher bgutil-ytdlp-pot-provider 2>/dev/null; then
    echo "[run] yt-dlp refreshed: $(/opt/ytdlp/bin/yt-dlp --version)"
  else
    echo "[run] yt-dlp refresh failed (offline?) — using the version baked into the image: $(/opt/ytdlp/bin/yt-dlp --version)"
  fi
) &

# --- receiver ---------------------------------------------------------------
export YTCR_DEVICE_NAME="$DEVICE_NAME"
export YTCR_DIAL_PORT="$DIAL_PORT"
export YTCR_AUDIO_DEVICE="pipewire/ytm-out"
export YTCR_YTDL_PATH=/opt/ytdlp/bin/yt-dlp
# node here, not quickjs: this image has node 22, which yt-dlp accepts (and which
# is ~4x faster than quickjs at the challenge). The armv7 Pi cannot, hence its
# different setting.
export YTCR_JS_RUNTIME=node
# Persisted in /data: the cookie jar is a live credential yt-dlp rewrites as
# cookies rotate, and node-persist keeps the DIAL identity next to it so the phone
# recognises the same device across restarts.
export YTCR_COOKIES=/data/cookies.txt
# yt-dlp's own on-disk cache, in /data so it survives container restarts and image
# updates. It holds the extracted signature functions and the downloaded ejs
# challenge-solver scripts — the part of a cold resolve that a *restart* would
# otherwise re-pay. The default (~/.cache/yt-dlp) is neither persistent here nor
# reliably writable.
export YTCR_YTDLP_CACHE_DIR=/data/yt-dlp-cache
export YTCR_LOG_LEVEL="$LOG_LEVEL"
[ -n "$CIPHER_URL" ] && export YTCR_CIPHER_URL="$CIPHER_URL"
[ -n "$POT_URL" ] && export YTCR_POT_URL="$POT_URL"
[ -n "$BIND_ADDRESS" ] && export YTCR_BIND_ADDRESS="$BIND_ADDRESS"
# The router add-on shares this host's network namespace, so its API is local.
# Exported unconditionally, because the admin page talks to that API too — it is how
# the RTP source gets created — so only the *reporting* is gated by the option.
export YTCR_ADDON_HOST="$RTP_HOST"
export YTCR_ADDON_API_PORT=8099
export YTCR_RTP_PORT="$RTP_PORT"
export YTCR_REPORT_METADATA="$REPORT_METADATA"

# The admin page (receiver/admin.js). This port MUST equal `ingress_port` in
# config.yaml — with host networking Supervisor proxies ingress straight to it, and a
# mismatch means a sidebar panel that loads nothing. Deliberately neither 8098 (this
# add-on's DIAL server) nor 8099 (the router's API), both already on this host.
export YTCR_ADMIN_PORT=8097
# Left on every interface, matching the router add-on's own UI: host networking means
# this page is then also reachable unauthenticated at <host>:8097, not just through
# ingress. Supervisor may well proxy ingress via 127.0.0.1 for a host-network add-on,
# in which case `export YTCR_ADMIN_BIND=127.0.0.1` would close that off entirely —
# worth confirming against a real instance before relying on it, because getting it
# wrong is a panel that loads nothing.

if [ ! -f "$YTCR_COOKIES" ]; then
  echo "[run] no cookie jar at $YTCR_COOKIES — resolving anonymously."
  echo "[run] Provision one with: firmware/pi-ytmusic/push_cookies.py --addon"
fi

mkdir -p /data/state
cd /data/state

# exec, so node becomes PID 1 and receives the supervisor's SIGTERM directly —
# its own handler stops the cast session and mpv cleanly. No forwarding needed.
exec node /app/index.js
