mod api;
mod config;
mod pw_config_gen;
mod pw_thread;
mod routing;
mod wyoming;

use clap::{Parser, Subcommand};
use std::path::PathBuf;

const DEFAULT_OPTIONS_PATH: &str = "/data/options.json";
const DEFAULT_CONF_D_PATH: &str = "/etc/pipewire/pipewire.conf.d/10-outputs.conf";
const DEFAULT_HTTP_ADDR: &str = "0.0.0.0:8080";

#[derive(Parser)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Render the static PipeWire conf.d snippet for configured RAOP
    /// outputs. Must run (and its output must exist) before `pipewire`
    /// itself starts — see pw_config_gen.rs for why this can't be done at
    /// runtime instead.
    GenerateConfig {
        #[arg(long, default_value = DEFAULT_OPTIONS_PATH)]
        options: PathBuf,
        #[arg(long, default_value = DEFAULT_CONF_D_PATH)]
        out: PathBuf,
    },
    /// Run the long-lived daemon: connect to the already-running PipeWire
    /// instance and serve the REST API.
    Serve {
        #[arg(long, default_value = DEFAULT_OPTIONS_PATH)]
        options: PathBuf,
        #[arg(long, default_value = DEFAULT_HTTP_ADDR)]
        listen: String,
    },
    /// Print every non-PipeWire/WirePlumber process `run.sh` needs to
    /// start, one per line, as tab-separated fields: `run.sh` shells out
    /// to this instead of re-implementing options.json parsing in bash.
    /// Lines:
    ///   airplay_source\t<display name>
    ///   sendspin_adapter\t<node name>\t<display name>\t<port>
    RuntimePlan {
        #[arg(long, default_value = DEFAULT_OPTIONS_PATH)]
        options: PathBuf,
    },
}

fn main() -> anyhow::Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "bridge_daemon=info".into()),
        )
        .init();

    let cli = Cli::parse();
    match cli.command {
        Command::GenerateConfig { options, out } => generate_config(&options, &out),
        Command::Serve { options, listen } => serve(&options, &listen),
        Command::RuntimePlan { options } => runtime_plan(&options),
    }
}

fn runtime_plan(options_path: &std::path::Path) -> anyhow::Result<()> {
    let options = config::AddonOptions::load(options_path)?;
    for component in options.runtime_components() {
        match component {
            config::RuntimeComponent::AirplaySource { display_name } => {
                println!("airplay_source\t{display_name}");
            }
            config::RuntimeComponent::SendspinAdapter {
                node_name,
                display_name,
                port,
            } => {
                println!("sendspin_adapter\t{node_name}\t{display_name}\t{port}");
            }
        }
    }
    Ok(())
}

fn generate_config(options_path: &std::path::Path, out_path: &std::path::Path) -> anyhow::Result<()> {
    let options = config::AddonOptions::load(options_path)?;
    let rendered = pw_config_gen::render(&options);
    if let Some(parent) = out_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(out_path, rendered)?;
    tracing::info!(
        "wrote PipeWire config for {} output(s) to {}",
        options.outputs.len(),
        out_path.display()
    );
    Ok(())
}

fn serve(options_path: &std::path::Path, listen: &str) -> anyhow::Result<()> {
    // Config is loaded here too (even though pipewire.conf.d was already
    // generated by a prior `generate-config` run) so the API can eventually
    // report on outputs the user configured but that haven't shown up in
    // the PipeWire registry yet (e.g. misconfigured IP) — not used for that
    // yet in this skeleton, but loading it now avoids a second entrypoint
    // convention later.
    let options = config::AddonOptions::load(options_path)?;
    tracing::info!("loaded {} configured output(s)", options.outputs.len());

    let (pw_state, changes) = pw_thread::spawn()?;

    let rt = tokio::runtime::Runtime::new()?;
    rt.block_on(async {
        let app = api::router(pw_state, changes);
        let listener = tokio::net::TcpListener::bind(listen).await?;
        tracing::info!("listening on {listen}");
        axum::serve(listener, app).await?;
        Ok::<(), anyhow::Error>(())
    })
}
