//! Generates the static `pipewire.conf.d/*.conf` snippet for configured RAOP
//! outputs.
//!
//! Why static config generation instead of loading modules at runtime: the
//! PipeWire core protocol (`pw_core_methods` in `core.h`) has no
//! `load_module` RPC at all — confirmed by reading the actual protocol
//! header, not assumed. Modules like `raop-sink` can only be loaded from the
//! daemon's own config at process start. This file's output must exist
//! *before* `pipewire` starts; changing outputs means regenerating this file
//! and restarting the add-on, which matches standard Home Assistant add-on
//! UX (most add-ons already work this way for config changes).

use crate::config::{slugify, AddonOptions};
use std::fmt::Write as _;

/// Node name prefix so generated RAOP sink nodes are easy to recognize/filter
/// in `pw-dump`/`pw-link` output and in this daemon's own registry queries.
pub const RAOP_NODE_PREFIX: &str = "raop-out-";

pub fn raop_node_name(output_name: &str) -> String {
    format!("{RAOP_NODE_PREFIX}{}", slugify(output_name))
}

/// Renders the full `pipewire.conf.d` snippet content for every configured
/// RAOP output. Empty (but valid) content if there are no outputs yet.
pub fn render(options: &AddonOptions) -> String {
    let mut out = String::new();
    writeln!(out, "# Generated by bridge-daemon generate-config. Do not edit by hand —").unwrap();
    writeln!(out, "# regenerate from the add-on's configured outputs instead.").unwrap();
    writeln!(out, "context.modules = [").unwrap();
    for output in &options.outputs {
        let node_name = raop_node_name(&output.name);
        writeln!(out, "    {{ name = libpipewire-module-raop-sink").unwrap();
        writeln!(out, "        args = {{").unwrap();
        writeln!(out, "            raop.ip = \"{}\"", output.ip).unwrap();
        writeln!(out, "            raop.port = {}", output.port).unwrap();
        writeln!(out, "            raop.name = \"{}\"", output.name).unwrap();
        writeln!(out, "            raop.transport = \"udp\"").unwrap();
        writeln!(
            out,
            "            raop.encryption.type = \"{}\"",
            output.encryption.as_pipewire_arg()
        )
        .unwrap();
        writeln!(out, "            audio.format = \"S16\"").unwrap();
        writeln!(out, "            audio.rate = 44100").unwrap();
        writeln!(out, "            audio.channels = 2").unwrap();
        writeln!(out, "            node.name = \"{node_name}\"").unwrap();
        writeln!(out, "        }}").unwrap();
        // nofail: one misconfigured device must not take the whole daemon
        // down — confirmed necessary in spikes/02-raop-static-sink.md.
        writeln!(out, "        flags = [ nofail ]").unwrap();
        writeln!(out, "    }}").unwrap();
    }
    writeln!(out, "]").unwrap();
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{RaopEncryption, RaopOutputConfig};

    #[test]
    fn renders_one_output_with_auth_setup_default() {
        let options = AddonOptions {
            outputs: vec![RaopOutputConfig {
                name: "Pioneer VSX-934".to_string(),
                ip: "192.168.178.35".to_string(),
                port: 7000,
                encryption: RaopEncryption::AuthSetup,
            }],
            ..Default::default()
        };
        let rendered = render(&options);
        assert!(rendered.contains("raop.ip = \"192.168.178.35\""));
        assert!(rendered.contains("raop.port = 7000"));
        assert!(rendered.contains("raop.encryption.type = \"auth_setup\""));
        assert!(rendered.contains("node.name = \"raop-out-pioneer_vsx_934\""));
        assert!(rendered.contains("flags = [ nofail ]"));
    }

    #[test]
    fn renders_empty_but_valid_config_with_no_outputs() {
        let options = AddonOptions::default();
        let rendered = render(&options);
        assert_eq!(rendered.trim(), "# Generated by bridge-daemon generate-config. Do not edit by hand —\n# regenerate from the add-on's configured outputs instead.\ncontext.modules = [\n]".trim());
    }
}
